# Generated by Django 2.0.5 on 2018-05-21 07:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ds_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 21, 7, 34, 31, 574348, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
