# Generated by Django 2.0.5 on 2018-05-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_test', '0002_book_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('path', models.CharField(blank=True, max_length=2000, null=True)),
                ('method', models.CharField(max_length=7)),
                ('protocol', models.CharField(blank=True, max_length=64, null=True)),
                ('remote_addr', models.CharField(blank=True, max_length=64, null=True)),
                ('http_user_agent', models.TextField(blank=True, null=True)),
                ('response_status', models.PositiveIntegerField()),
            ],
        ),
    ]
