# Generated by Django 2.0.5 on 2018-05-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_test', '0003_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('edit', 'edit'), ('create', 'create'), ('delete', 'delete')], max_length=6)),
                ('old_data', models.TextField(blank=True, default=None, null=True)),
                ('new_data', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
